spring.application.name=Inventory-Management-System

server.port = ${PORT:8080}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/InventoryManagement
spring.datasource.username=root
spring.datasource.password=waminisce
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
file.upload-dir=uploads
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
jwt.secret=myInventorySystemSuperSecretKey2024!!


spring.mail.host = smtp.gmail.com
spring.mail.port = 465
spring.mail.username = onidareadewaleoluwafemi69@gmail.com
spring.mail.password = wrrpzfcxfjiazdsb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true

